development:
  adapter: postgresql
  encoding: unicode
  database: rails_ecommerce_development
  pool: 5
  host: localhost
  username: "postgres"
  password: "12345678"

test:
  adapter: postgresql
  encoding: unicode
  database: rails_ecommerce_test
  pool: 5
  username: "postgres"
  password: "12345678"

# staging:
#   url: <%= ENV['DATABASE_URL'] %>

# production:
#   url: <%= ENV['DATABASE_URL'] %> 